### ISSUE TITLE
Workshop presentation

### ISSUE THREAD

**Issue by yuhanjiang02** [InterlabsOCWA/CodeDocumentation#7]
- Pull request section might edit/write later. Don't need pull request for each branch workflow 
- Move create repository and branch section to fundamental branch workflow
- Explain commit hash
- Add more on the Version control project workflow and General each branch workflow section
- Main file naming and check out for Rpoj

**Comment by InterlabsOCWA** [comment]
* prepare the two story walkthrough's (how we interact with git/github through a round, through a feature or refactor)
* explain checkout (or why we shouldn't do it for now?)
* separate graphic as needed to illustrate 1) branches configuration, 2) what happens within a round or within a develop/refactor weekly cycle
* provide a workshop prep slide & link to the code doc section (on the internet) to help Alex & Chris pre-install what they need
* explain git clone and what it means to work locally vs. a remote repository.  Difference from network drive being an archival location that we save to during the "milestone merger workshop" (giving it that name in lieu of probably a real techy term)

**Comment by jjyh** [comment]
partial notes from today's meeting
installation slide
step 3 - use interlabs email but their own name
step 4 - optional

connect slide - 
- what's on github?  (what's not on there & why)
- help everyone git clone the base code onto local
- how to open up on RStudio properly - git tab 
- switch branch in the corner (more details in later session)

add renv

detect (? see if git tab shows on Rstudio)\

Version Control
move location to new slide and explain difference of the three working locations
graphic - make clear there are three paths (indent the sub-branches and use colour)

Folder Location
Make linkage clear - repository = stage

Create branch - 
add way to create branch
- issues tracking & kanban

Demo time
add breaks for questions
add more on git status ("help")

**Comment by jjyh** [comment]
@yuhanjiang02  
1) graphic change (update frequency in the right bottom corner) - re-word "after main change" because that sounds like you're referring to main branch.  add the dot graphic to commit, so if someone were reading the slides without your verbal explanation, they will understand dots = commit
2) gitignore slide - what does the bullet "all the data spreadsheet - Not sure, might be different" mean?  Re-word.  Also note that outputs which reveals results should be git-ignored.
3) main branch - inside or right after the caution note can you add a link to the later slide (switch-to-corresponding-branch), again assuming audience e.g. Alex needs to refer to slide and not present for your live demo
4) git pull and git status slides - since there is space there could you provide graphic of they look like, or better yet, what message could return from the command and how to understand or resolve them
5) after the "merge conflict" slide, can you create a new slide summarizing all the actions you've taught in one page - clone, pull, commit push status etc.
6) post this online in github pages or wix if possible ahead of the workshop
As an aside - be prepared to tell the story of how things work in a round etc.  add speaker notes to help yourself if needed
